---
#### This file contains the build pipeline for the eSIM LEAP Infrastructure and
###  application code deployment pipeline.
## The Pipeline view values:
#     Name:
#         "Test eSIM Deployment Pipeline"
#     Description:
#         ""
#     Build Pipeline View Title:
#         "Test eSIM Deployment"

# You should create one project per product and link all the steps

- project:
    name: test_esim-aws
    disabled: false
    platform_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    platform_code_repository_display_name: eSIM Jenkins
    platform_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    platform_code_repository_name: vfdo-esim-platform
    platform_code_repository_type: git
    platform_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfdo-esim-platform.git
    ## as desired in prod JJB
    # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    # platform_code_repository_branches: origin/tags/Release-*
    #
    ## useful for testing platform code from a branch
    # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    # platform_code_repository_branches: origin/deploy_platformtest_env
    ## Two lines below set as work around because we can't push to master
    ## without PR.
    ## An attempt to get dev, systemtest and staging rebuilt with updated
    ## CIDR ranges over weekend.
    platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    #platform_code_repository_branches: origin/integration/EAP-6133_new_pipeline_prerelease_test
    #platform_code_repository_branches: origin/fix/integration/EAP-6133_new_pipeline_prerelease_test
    #platform_code_repository_branches: origin/fix/integration/EAP-6133_new_pipeline_prerelease_test_ssl_cert_issue
    #platform_code_repository_branches: origin/integration/EAP-6133_new_pipeline_prerelease_test_peering
    #platform_code_repository_branches: origin/integration/EAP-6133_new_pipeline_prerelease_test_remove_opco_s3_buckets_and_ldap_value_injections
    #platform_code_repository_branches: origin/feature/EAP-3637_Custom_Domain_Setup_for_eSIM
    platform_code_repository_branches: origin/feature/EAP-3637_Custom_Domain_Setup_for_eSIM_Jenkins_wake_up
    #
    # useful for testing platform code from master head
    # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    # platform_code_repository_branches: origin/master
    app_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    app_code_repository_display_name: eSIM Jenkins
    app_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    app_code_repository_name: vfleap
    app_code_repository_type: git
    app_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfleap_repository.git
    artefact_version_prefix: T
    initial_deployment_target: ovfpftesta
    workspace_clone_glob: 'LEAP/**'
    js_app_file: vfleap.js
    repo_language: nodejs
    nodejs_version: 6.9.1
    jobs:
      - '{name}-checkout-code-master'
      - '{name}-checkout-platform-code'
      - '{name}-build-artefact'
      - '{name}-provision-{environment}':
            environment: ovfpftesta
      - '{name}-configure-{environment}':
            environment: ovfpftesta
            playbook: test.yml
      - '{name}-deploy-to-{environment}':
            environment: ovfpftesta
      - '{name}-test-{environment}':
            environment: ovfpftesta
            next_environment: ovfpftestb
      - '{name}-provision-{environment}':
            environment: ovfpftestb
      - '{name}-configure-{environment}':
            environment: ovfpftestb
            playbook: test.yml
      - '{name}-deploy-to-{environment}':
            environment: ovfpftestb
      - '{name}-test-{environment}':
            environment: ovfpftestb
            next_environment: none
