---
#### This file contains the build pipeline for the eSIM LEAP Infrastructure and
###  application code deployment pipeline.
## The Pipeline view values:
#     Name:
#         "eSIM A Deployment Pipeline"
#     Description:
#         ""
#     Build Pipeline View Title:
#         "eSIM A Deployment Pipeline"

# You should create one project per product and link all the steps

# - project:
#     name: test_esim-aws-a
#     platform_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
#     platform_code_repository_display_name: eSIM Jenkins
#     platform_code_repository_display_email: vodafone-devops-internal@devopsguys.com
#     platform_code_repository_name: vfdo-esim-platform
#     platform_code_repository_type: git
#     platform_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfdo-esim-platform.git
#     ### uncomment below for standard deployment from a release of Platform code.
#     # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
#     # platform_code_repository_branches: origin/tags/Release-*
#     ## Two lines below set as work around because we can't push to master
#     ## without PR.
#     ## An attempt to get dev, systemtest and staging rebuilt with updated
#     ## CIDR ranges over weekend.
#     platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
#     platform_code_repository_branches: origin/integration/VFESIM-277_FreeIPA_gateway_fix
#     #platform_code_repository_branches: origin/release/2.0.0
#     app_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
#     app_code_repository_display_name: eSIM Jenkins
#     app_code_repository_display_email: vodafone-devops-internal@devopsguys.com
#     app_code_repository_name: vfleap
#     app_code_repository_type: git
#     app_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfleap_repository.git
#     artefact_version_prefix: TA
#     initial_deployment_target: TO_BE_CONFIRMED
#     workspace_clone_glob: 'LEAP/**'
#     js_app_file: vfleap.js
#     repo_language: nodejs
#     nodejs_version: 6.9.1
#     jobs:
#       - '{name}-checkout-code-master'
#       - '{name}-checkout-platform-code'
#       - '{name}-build-artefact'
#       - '{name}-provision-{environment}':
#             environment: TO_BE_CONFIRMED
#       - '{name}-configure-{environment}':
#             environment: TO_BE_CONFIRMED
#             #playbook: temp-openldap.yml
#             playbook: test-app-vpc-connectivity.yml
#       - '{name}-deploy-to-{environment}':
#             environment: TO_BE_CONFIRMED
#             next_environment: none
