---
#### This file contains the build pipeline for the eSIM LEAP Infrastructure and
###  application code deployment pipeline for branches.
## The Pipeline view values:
#     Name:
#         "eSIM Deployment Branches Pipeline"
#     Description:
#         "This pipeline packages and deploys from the App Code branches."
#     Build Pipeline View Title:
#         "eSIM Deployment Branches"
# You should create one project per product and link all the steps

- project:
    name: esim-aws-branches
    config_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    config_code_repository_display_name: eSIM Jenkins
    config_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    config_code_repository_name: vfdo-esim-platform
    config_code_repository_type: git
    config_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfdo-esim-platform.git
    app_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    app_code_repository_display_name: eSIM Jenkins
    app_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    app_code_repository_name: vfleap
    app_code_repository_type: git
    app_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfleap_repository.git
    artefact_version_prefix: B
    initial_deployment_target: preprod
    workspace_clone_glob: 'LEAP/**'
    js_app_file: vfleap.js
    repo_language: nodejs
    jobs:
      - '{name}-checkout-code-branches'
      - '{name}-build-artefact'
      - '{name}-deploy-to-{environment}':
          environment: preprod
          next_environment: none





      ###
      # below was the intention
      ##
      # - '{name}-deploy-to-branches-{environment}':
      #     environment: branchesdev
      #     next_environment: branchessystemtest
      # - '{name}-deploy-to-branches-{environment}':
      #     environment: branchessystemtest
      #     next_environment: none
