---
#### This file contains the build pipeline for the eSIM LEAP Infrastructure and
###  application code deployment pipeline.
## The Pipeline view values:
#     Name:
#         "Test eSIM Deployment Pipeline"
#     Description:
#         ""
#     Build Pipeline View Title:
#         "Test eSIM Deployment"

# You should create one project per product and link all the steps

- project:
    name: test_esim-aws
    disabled: false
    platform_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    platform_code_repository_display_name: eSIM Jenkins
    platform_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    platform_code_repository_name: vfdo-esim-platform
    platform_code_repository_type: git
    platform_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfdo-esim-platform.git
    ## as desired in prod JJB
    platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    platform_code_repository_branches: origin/tags/Release-*
    #
    ## useful for testing platform code from a branch
    # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    # platform_code_repository_branches: origin/deploy_platformtest_env
    #
    ## useful for testing platform code from master head
    # platform_code_repository_refspec: +refs/tags/*:refs/remotes/origin/tags/*
    # platform_code_repository_branches: origin/master
    app_code_repository_credentials: 10b4587a-9464-4766-9207-be5f4a03dc00
    app_code_repository_display_name: eSIM Jenkins
    app_code_repository_display_email: vodafone-devops-internal@devopsguys.com
    app_code_repository_name: vfleap
    app_code_repository_type: git
    app_code_repository_uri: ssh://git@platform.devops.vodafone.com:7999/vfleap/vfleap_repository.git
    artefact_version_prefix: T
    initial_deployment_target: platformtest
    workspace_clone_glob: 'LEAP/**'
    js_app_file: vfleap.js
    repo_language: nodejs
    jobs:
      - '{name}-checkout-code-master'
      - '{name}-checkout-platform-code'
      - '{name}-build-artefact'
      - '{name}-provision-{environment}':
            environment: platformtest
      - '{name}-configure-{environment}':
            environment: platformtest
      - '{name}-deploy-to-{environment}':
            environment: platformtest
            next_environment: platformtestb
      - '{name}-provision-{environment}':
            environment: platformtestb
      - '{name}-configure-{environment}':
            environment: platformtestb
      - '{name}-deploy-to-{environment}':
          environment: platformtestb
          next_environment: none
