---
- job-template:
    name: '{name}-provision-{environment}'
    parameters:
      - string:
          name: PIPELINE_NUMBER
          default: ""
          description: "The BUILD_NUMBER of first job in the pipeline"
      - string:
          name: APP_GIT_COMMIT
          default: ""
          description: "The git commit of the VFLEAP repository"
      - string:
          name: APP_GIT_BRANCH
          default: ""
          description: "The git branch of the VFLEAP repository"
      - string:
          name: ARTEFACT_VERSION
          default: ""
          description: "The artefact version to deploy"
      - string:
          name: PLATFORM_RELEASE_COMMIT_ID
          default: ""
          description: "The git commit of the latest release in the vfdo-esim-platform repository."
      - string:
          name: PLATFORM_RELEASE_BRANCH
          default: ""
          description: "The git branch/tag name of the latest release in the vfdo-esim-platform repository."
    project-type: freestyle
    defaults: global
    description: 'Do not edit this job through the web!'
    disabled: false
    display-name: 'Provison {environment} environment.'
    node: '{name}'
    properties:
      - build-discarder:
          days-to-keep: 365
          num-to-keep: 100
      - inject:
          properties-content: |
            ENVIRONMENT={environment}
            ARTEFACT_VERSION={{ARTEFACT_VERSION}}
    wrappers:
      - ansicolor
    scm:
      - '{platform_code_repository_type}':
          refspec: '{platform_code_repository_refspec}'
          url: '{platform_code_repository_uri}'
          branches:
            - ${{PLATFORM_RELEASE_BRANCH}}
          credentials-id: '{platform_code_repository_credentials}'
          git-config-name: '{platform_code_repository_display_name}'
          git-config-email: '{platform_code_repository_display_email}'
          timeout: 5
    wrappers:
      - ssh-agent-credentials:
            users:
                - '{platform_code_repository_credentials}'
    builders:
        - shell: !include-raw-escape: utility-echo-git-plugin-environment-variables.sh
        - shell: !include-raw-escape: utility-echo-current-parameters-environment-variables.sh
        - shell: echo "Provisioning environment ${{ENVIRONMENT}}"
      # - shell: !include-raw-escape: provision-environment.sh
    publishers:
      - trigger-parameterized-builds:
          - project:
              - '{name}-deploy-to-{initial_deployment_target}'
            current-parameters: true
            condition: SUCCESS
